### ISSUE TITLE
Documentation $TRAEFIK_SERVICE does not match actual service

### ISSUE THREAD

**Issue by codemonkeysoftware** [RealOrangeOne/traefik-pages#1]
Currently the documentation lists the $TRAEFIK_SERVICE as `traefik-pages@docker`, but the service is created using a file and is therefore `traefik-pages@file` so traefik cannot find the service. Either $TRAEFIK_SERVICE should point to the file service or the docker-compose example should include tags to create the docker service.

I'm happy to submit an MR for the change, but thought you might have a preference for which solution was used.

Thanks for building this, btw. It's really handy.

**Comment by RealOrangeOne** [comment]
Ah I see what the problem is. It's mixed up a few examples whilst I was building it.

The solution is to remove the file provider entirely, and instead set `traefik.enable=true` on the pages container, so it then _is_ defined in docker. That's how [I've deployed it](https://github.com/RealOrangeOne/infrastructure/blob/master/ansible/roles/pages/files/docker-compose.yml#L30).

I'd absolutely welcome a PR for this! :smile:

**Comment by lpdyck** [comment]
Same. I didn't even think to look at your deployment code, though. I just wasted a half an hour figuring it out on my own :facepalm:
